### ISSUE TITLE
Could not find session cookie when booting up HA.

### ISSUE THREAD

**Issue by jampez77** [ljmerza/ha-our-groceries#17]
## Version of the custom_component
1.3.6

## Configuration

```yaml

ourgroceries:
      username: !secret jamie_email
      password: !secret our_groceries_password

```

## Describe the bug
This morning OG will not work with HA. I upgraded from `core-2021.3.4` to `core-2021.4.0` and immediately recieved the following error.

I tried to revert back to last known working back up but the problem still persists. 
## Debug log

```text
2021-04-08 09:11:13 WARNING (MainThread) [homeassistant.loader] You are using a custom integration ourgroceries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-08 09:11:13 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'ourgroceries'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'ourgroceries'
2021-04-08 09:11:17 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'media_player', 'device_tracker', 'shopping_list', 'alexa_media', 'panel_iframe', 'ourgroceries', 'notify', 'ring', 'logbook', 'map', 'homekit', 'group', 'zeroconf', 'mail_and_packages', 'sonoff', 'profiler', 'ffmpeg', 'openweathermap', 'script', 'camera', 'nodered', 'tts', 'xbox', 'automation', 'zone', 'scheduler', 'python_script', 'sun', 'input_boolean', 'conversation', 'blueprint', 'tasmota', 'switch', 'my', 'history', 'tag', 'tuya', 'input_select', 'zha', 'mqtt', 'weather', 'input_text', 'persistent_notification', 'input_datetime', 'hacs', 'system_health', 'rest_command', 'input_number', 'updater', 'binary_sensor', 'skyq', 'mobile_app', 'upnp', 'fullykiosk', 'sensor', 'ipp', 'ios', 'discovery', 'google'}
2021-04-08 09:11:17 INFO (MainThread) [homeassistant.setup] Setting up ourgroceries
2021-04-08 09:11:17 DEBUG (MainThread) [custom_components.ourgroceries] creating og instance
2021-04-08 09:11:17 DEBUG (MainThread) [custom_components.ourgroceries] logging into og
2021-04-08 09:11:17 DEBUG (MainThread) [ourgroceries] ourgroceries _get_session_cookie2021-04-08 09:11:26 ERROR (MainThread) [ourgroceries] ourgroceries Could not find cookie session
2021-04-08 09:11:26 ERROR (MainThread) [homeassistant.setup] Error during setup of component ourgroceries
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/ourgroceries/__init__.py", line 66, in async_setup
    await og.login()
  File "/usr/local/lib/python3.8/site-packages/ourgroceries/__init__.py", line 78, in login
    await self._get_session_cookie()
  File "/usr/local/lib/python3.8/site-packages/ourgroceries/__init__.py", line 98, in _get_session_cookie
    raise InvalidLoginException('Could not find session cookie')
ourgroceries.exceptions.InvalidLoginException: Could not find session cookie
2021-04-08 09:11:27 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=persistent_notification, service=create, service_data=title=Invalid config, message=The following integrations and platforms could not be set up:

 - [ourgroceries](https://www.home-assistant.io/components/our-groceries)

Please check your config and [logs](/config/logs)., notification_id=invalid_config>
2021-04-08 09:11:27 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=persistent_notification.invalid_config, old_state=None, new_state=<state persistent_notification.invalid_config=notifying; title=Invalid config, friendly_name=Invalid config, message=The following integrations and platforms could not be set up:

 - [ourgroceries](https://www.home-assistant.io/components/our-groceries)

Please check your config and [logs](/config/logs). @ 2021-04-08T09:11:27.873782+01:00>>

```
```text
Logger: homeassistant.setup
Source: custom_components/ourgroceries/__init__.py:66
First occurred: 8:51:45 (1 occurrences)
Last logged: 8:51:45

Error during setup of component ourgroceries
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/ourgroceries/__init__.py", line 66, in async_setup
    await og.login()
  File "/usr/local/lib/python3.8/site-packages/ourgroceries/__init__.py", line 78, in login
    await self._get_session_cookie()
  File "/usr/local/lib/python3.8/site-packages/ourgroceries/__init__.py", line 98, in _get_session_cookie
    raise InvalidLoginException('Could not find session cookie')
ourgroceries.exceptions.InvalidLoginException: Could not find session cookie
```

**Comment by Drewskieza** [comment]
Same issue on my side.

**Comment by rpitera** [comment]
Same issue here; I'm still on core-2021.3.4 and haven't upgraded yet.  Reinstalled, also deleted and reinstalled but no difference. For me this started happening after a restart last night.

**Comment by ljmerza** [comment]
so unfortunately, our groceries also redesigned their site breaking the python library. the python library is an unofficial api. our groceries has split their login screen so you have to submit your username then submit your password. im sure there's a way to get around this but its not a quick fix.

**Comment by ljmerza** [comment]
fixed in v1.3.8

**Comment by rpitera** [comment]
Wow, that was faster than expected!!  Thanks buddy!

**Comment by rpitera** [comment]
Just bought you a couple of coffees; wish I could afford more!

**Comment by Kippy74** [comment]
And today it happened once again..

”Our groceries - Could not find coocie session”

Any ideas how to fix this?
