### ISSUE TITLE
Beta 2023.9.0B5 Caused error in code

### ISSUE THREAD

**Issue by bschatzow** [ljmerza/ha-our-groceries#39]
## Configuration

```yaml
ourgroceries:
  username: !secret our_groceries_username
  password: !secret our_groceries_password
Add your logs here.

```

## Describe the bug
New error on today's beta.  I assume this will be released as is tomorrow.

## Debug log

```text

Logger: homeassistant.setup
Source: custom_components/ourgroceries/__init__.py:66
Integration: Our Groceries
First occurred: 7:59:35 PM (1 occurrences)
Last logged: 7:59:35 PM

Error during setup of component ourgroceries
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/ourgroceries/__init__.py", line 66, in async_setup
    await og.login()
  File "/usr/local/lib/python3.11/site-packages/ourgroceries/__init__.py", line 109, in login
    await self._get_master_list_id()
  File "/usr/local/lib/python3.11/site-packages/ourgroceries/__init__.py", line 151, in _get_master_list_id
    self._master_list_id = re.findall(REGEX_MASTER_LIST_ID, responseText)[0]
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^

```

**Comment by bschatzow** [comment]
Still broke in the 2023.9.0 release.

**Comment by waynetd777** [comment]
I'm also experiencing this issue since upgrading HA Core to 2023.9.0. A fix would be much appreciated.

**Comment by MerekW** [comment]
Just adding here (thank you for the work!!):

Logger: homeassistant.setup
Source: custom_components/ourgroceries/__init__.py:66
Integration: ourgroceries
First occurred: 02:56:41 (1 occurrences)
Last logged: 02:56:41

Error during setup of component ourgroceries
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/ourgroceries/__init__.py", line 66, in async_setup
    await og.login()
  File "/usr/local/lib/python3.11/site-packages/ourgroceries/__init__.py", line 109, in login
    await self._get_master_list_id()
  File "/usr/local/lib/python3.11/site-packages/ourgroceries/__init__.py", line 151, in _get_master_list_id
    self._master_list_id = re.findall(REGEX_MASTER_LIST_ID, responseText)[0]
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by gNusd** [comment]
I have the same problem after upgrading to 2023.9. Looks like problem with regex.

Logger: homeassistant.setup
Source: custom_components/ourgroceries/__init__.py:66
Integration: ourgroceries
First occurred: 17:06:49 (1 occurrences)
Last logged: 17:06:49

Error during setup of component ourgroceries
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/ourgroceries/__init__.py", line 66, in async_setup
    await og.login()
  File "/usr/local/lib/python3.11/site-packages/ourgroceries/__init__.py", line 109, in login
    await self._get_master_list_id()
  File "/usr/local/lib/python3.11/site-packages/ourgroceries/__init__.py", line 151, in _get_master_list_id
    self._master_list_id = re.findall(REGEX_MASTER_LIST_ID, responseText)[0]
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by ikeurb** [comment]
I am seeing the same error when starting HA:

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/ourgroceries/__init__.py:66
Integration: ourgroceries
First occurred: 11:37:24 AM (1 occurrences)
Last logged: 11:37:24 AM

Error during setup of component ourgroceries
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/ourgroceries/__init__.py", line 66, in async_setup
    await og.login()
  File "/usr/local/lib/python3.11/site-packages/ourgroceries/__init__.py", line 109, in login
    await self._get_master_list_id()
  File "/usr/local/lib/python3.11/site-packages/ourgroceries/__init__.py", line 151, in _get_master_list_id
    self._master_list_id = re.findall(REGEX_MASTER_LIST_ID, responseText)[0]
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by waynetd777** [comment]
@ljmerza Thank you for all the hard work on this integration! Any chance you can implement a fix for this issue please?

**Comment by ljmerza** [comment]
added

**Comment by neilmartin83** [comment]
@ljmerza Thank you for the merge, confirmed working for me - integration/service calls and sensor all good after a HA restart. :)

**Comment by bschatzow** [comment]
Fixed now
